/**
 * Exports the ABIs the web UI needs into `web/lib/abis.ts`.
 *
 * Keeping this generated (instead of hand-copied) guarantees the frontend always decodes
 * the exact event signatures the deployed contracts emit.
 */
const fs = require("fs");
const path = require("path");

const artifacts = [
  { contract: "SimpleAMM", exportName: "simpleAmmAbi" },
  { contract: "SimpleAMMFactory", exportName: "simpleAmmFactoryAbi" },
  { contract: "MockERC20", exportName: "mockErc20Abi" },
];

const ARTIFACTS_DIR = path.join(__dirname, "..", "artifacts", "contracts");
const OUTPUT_FILE = path.join(__dirname, "..", "web", "lib", "abis.ts");

function loadAbi(contract) {
  const artifactPath = path.join(
    ARTIFACTS_DIR,
    `${contract}.sol`,
    `${contract}.json`
  );

  if (!fs.existsSync(artifactPath)) {
    throw new Error(
      `Missing artifact for ${contract}. Run "npx hardhat compile" first.`
    );
  }

  return JSON.parse(fs.readFileSync(artifactPath, "utf8")).abi;
}

function main() {
  const sections = artifacts.map(({ contract, exportName }) => {
    const abi = JSON.stringify(loadAbi(contract), null, 2);
    return `export const ${exportName} = ${abi} as const;\n`;
  });

  const header = [
    "// AUTO-GENERATED by scripts/export-abis.js -- do not edit by hand.",
    "// Regenerate with: npm run export-abis",
    "",
  ].join("\n");

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, `${header}\n${sections.join("\n")}`);

  console.log(`Wrote ${path.relative(process.cwd(), OUTPUT_FILE)}`);
}

main();
